
--ALTER PROCEDURE [DAVE_MIGRATION].[RVRS_Load_Dave_Death_Generic_Load_Master_ScramblePr]
IF EXISTS(SELECT 1 FROM sys.Objects WHERE [OBJECT_ID]=OBJECT_ID('[DAVE_MIGRATION].[RVRS_Load_Dave_Death_Generic_Load_Master_ScramblePr]') AND [type]='P')
	DROP PROCEDURE [DAVE_MIGRATION].[RVRS_Load_Dave_Death_Generic_Load_Master_ScramblePr]
GO 

CREATE PROCEDURE [DAVE_MIGRATION].[RVRS_Load_Dave_Death_Generic_Load_Master_ScramblePr]
AS  

SELECT DEATH_REC_ID,INTERNAL_CASE_NUMBER,SFN_NUM
,(CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT(DATETIME , DOD)),112 )
+ (CASE WHEN CERT_DESIG = 'MEDICAL EXAMINER' THEN
			CAST((CASE WHEN TOD_IN_ME = 'P' AND TOD_ME NOT LIKE '12:%' THEN CAST(CAST(LEFT(REPLACE(TOD_ME,':',''),2) AS INT)+12 AS VARCHAR(100)) +CAST(RIGHT(REPLACE(TOD_ME,':',''),2) AS VARCHAR(100))
						WHEN TOD_IN_ME = 'D' AND TOD_ME = '12:00' THEN '0000'
						ELSE REPLACE(ISNULL(TOD_ME,'6666'),':','') 
						END) AS VARCHAR(10))
			WHEN TOD_IN = 'D' AND TOD = '12:00' THEN '0000'
			ELSE CAST((CASE WHEN TOD_IN = 'P'  AND TOD NOT LIKE '12:%' THEN CAST(CAST(LEFT(REPLACE(TOD,':',''),2) AS INT)+12 AS VARCHAR(100)) +CAST(RIGHT(REPLACE(TOD,':',''),2) AS VARCHAR(100))
			ELSE REPLACE(ISNULL(TOD,'6666'),':','') END) AS VARCHAR(10))
		END)
+'|||'+ SFN_NUM + '|' 
--+ CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , RECORD_REGIS_DATE)),112 ) +'6666'
+ CASE WHEN ISDATE(RECORD_REGIS_DATE)= 1 THEN CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , RECORD_REGIS_DATE)),112 ) +'6666'
	WHEN ISDATE(RECORD_REGIS_DATE) = 0 THEN REPLACE ((RIGHT(RECORD_REGIS_DATE,4) + LEFT(RECORD_REGIS_DATE,6)),'/','') + '6666'
	WHEN RECORD_REGIS_DATE IS NULL THEN ''
	END + '|' 
+ CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , VRV_REC_DATE_CREATED)),112 ) + '' + REPLACE(LEFT(CAST(CONVERT (TIME , VRV_REC_DATE_CREATED) AS VARCHAR (20)),6),':','')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'') 
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LNAME_MAIDEN,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'') 
+ '||'+ ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(GNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'') 
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')  
+ '|||' + ISNULL(SUFF,'') +'||'
+ CASE WHEN SEX ='M' THEN 'Male'
	   WHEN SEX = 'F' THEN 'Female'
	   WHEN SEX = 'U' THEN 'Unknown'
	   WHEN SEX IS NULL THEN ''
  END +'|'
+ CASE  WHEN DOB LIKE '99/99/9999' THEN '999999999999' + '|'					
		WHEN ISDATE(DOB)= 1 THEN CONVERT (VARCHAR(8),DATEADD(DAY,+2,CONVERT(DATETIME, DOB)),112) + '6666' + '|' 
		WHEN ISDATE(DOB)= 0 THEN REPLACE ((RIGHT(DOB,4) + LEFT(DOB,6)),'/','') + '6666' + '|' 
		END
+ ISNULL(CAST(AGE3 AS VARCHAR(8)),'') +'|' 
+ ISNULL(CAST(AGE5  AS VARCHAR(8)),'')+'|' 
+ ISNULL(CAST(AGE4 AS VARCHAR(8)),'') +'|' 
+ ISNULL(CAST(AGE2 AS VARCHAR(8)),'') +'|' 
+ ISNULL(CAST(AGE1 AS VARCHAR(8)),'') +'|' 
+ ISNULL(REVERSE(LEFT(SSN,3))+REVERSE(SUBSTRING(SSN,5,2))+REVERSE(RIGHT(SSN,4)),'') + '|' 
+ CASE WHEN ARMED='Y' THEN 'Yes'
	   WHEN ARMED='N' THEN 'No'
	   WHEN ARMED='U' THEN 'Unknown'
	   WHEN ARMED IS NULL THEN ''
END 
+ '||' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA1_LNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA1_FNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'') 
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA1_MNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '||'+ ISNULL(AKA1_SUFFIX,'') 
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA2_LNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA2_FNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA2_MNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '||'+ ISNULL(AKA2_SUFFIX,'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA3_LNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA3_FNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA3_MNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '||'+ ISNULL(AKA3_SUFFIX,'') 
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA4_LNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA4_FNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AKA4_MNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '||'+ ISNULL(AKA4_SUFFIX,'') + '|||||||||||' 
+ CASE  WHEN DPLACE = 1 THEN 'Hospital - Inpatient' 
		WHEN DPLACE = 2 THEN 'Hospital - ER/Outpatient'
		WHEN DPLACE = 3 THEN 'Hospital - DOA'
		WHEN DPLACE = 4 THEN 'Decedent''s Residence'
		WHEN DPLACE = 5 THEN 'Hospice Facility'
		WHEN DPLACE = 6 THEN 'Nursing Home'
		WHEN DPLACE = 7 THEN 'Assisted Living Facility or Rest Home'
		WHEN DPLACE = 8 THEN 'Other'
		WHEN DPLACE = 9 THEN 'Unknown'
		WHEN DPLACE IS NULL THEN ''		END 
+ '|' + ISNULL(DHOSPITALL,'') +'||' 
--+ ISNULL(CAST(CAST(REVERSE(DADDR_NUM) AS INT) AS VARCHAR (20)),'')
+ CASE WHEN DADDR_NUM LIKE '%,%' THEN '99'
		WHEN ISNUMERIC(DADDR_NUM)=1 THEN ISNULL(CAST(CAST(REVERSE(REPLACE(DADDR_NUM,'.','')) AS BIGINT) AS VARCHAR (20)),'')
	   WHEN DADDR_NUM IS NULL THEN ''
	   ELSE '99'
  END
+ '|' + ISNULL(DSTREET_PREFIX,'') 
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(DADDR1,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(DSTREET_DESIG,'') +'|' + ISNULL(DSTREET_SUFFIX,'') +'|' + ISNULL(DADDR2,'') +'|' + ISNULL(DNAME_CITY,'') +'|' + ISNULL(DCOUNTY,'') +'|'+ ISNULL(DSTATEL,'') 
+ '|' + ISNULL(DZIP9,'') +'|'+ ISNULL(DCOUNTRY,'') +'|' + ISNULL(MED_REC_NUM,'') +'||' + ISNULL(INDUST,'') +'|' + ISNULL(OCCUP,'') + '||||' 
+ CASE WHEN DEDUC = 1 THEN '8th Grade or Less'
		WHEN DEDUC = 2 THEN '9th - 12th Grade, No Diploma'
		WHEN DEDUC = 3 THEN 'High School Graduate or GED Completed'
		WHEN DEDUC = 4 THEN 'Some College Credit, but no Degree'
		WHEN DEDUC = 5 THEN 'Certificate'
		WHEN DEDUC = 6 THEN 'Associate Degree'
		WHEN DEDUC = 7 THEN 'Bachelor''s Degree'
		WHEN DEDUC = 8 THEN 'Master''s Degree'
		WHEN DEDUC = 9 THEN 'Doctorate or Professional Degree'
		WHEN DEDUC = 10 THEN 'Unknown'
		WHEN DEDUC = 11 THEN 'Refused'
		WHEN DEDUC = 12 THEN 'Special Education'
		WHEN DEDUC IS NULL THEN '' END
+ '|||||||||||||||||||||||||||' 
--+ ISNULL(CAST(CAST(REVERSE(RES_ADDR_NUM) AS INT) AS VARCHAR (20)),'')
+ CASE WHEN RES_ADDR_NUM LIKE '%,%' THEN '99'
		WHEN ISNUMERIC(RES_ADDR_NUM)=1 THEN ISNULL(CAST(CAST(REVERSE(REPLACE(RES_ADDR_NUM,'.','')) AS BIGINT) AS VARCHAR (20)),'')
	   WHEN RES_ADDR_NUM IS NULL THEN ''
	   ELSE '99'
  END
+ '|'+ ISNULL(RES_STREET_PREFIX,'') 
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RES_ADDR1,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(RES_STREET_DESIG,'') +'|' + ISNULL(RES_STREET_SUFFIX,'') 
+ '|' + ISNULL(RES_ADDR2,'') 
+ '|' + CASE WHEN RES_LIMITS = 'Y' THEN 'Yes'
	   WHEN RES_LIMITS = 'N' THEN 'No'
	   WHEN RES_LIMITS = 'U' THEN 'Unknown'
	   WHEN RES_LIMITS IS NULL THEN ''
	   END
+ '|' + ISNULL(RES_CITY,'') + '|' + ISNULL(RES_COUNTY,'') 
+ '|' + ISNULL(RES_STATE,'') + '|' + ISNULL(RES_ZIP,'') + '|' + ISNULL(RES_COUNTRY,'') + '|' 
+ CASE WHEN MARITAL = 'M' THEN 'Married' 
		WHEN MARITAL = 'A' THEN 'Married - Separated'
		WHEN MARITAL = 'W' THEN 'Widowed'
		WHEN MARITAL = 'D' THEN 'Divorced'
		WHEN MARITAL = 'S' THEN 'Never Married'
		WHEN MARITAL = 'U' THEN 'Unknown' 
		WHEN MARITAL IS NULL THEN '' END
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SPOUSE_LNAME_PRIOR,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SPOUSE_GNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SPOUSE_MNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SPOUSE_SUFFIX,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FATHER_LNAME_PRIOR,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FATHER_GNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FATHER_MNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FATHER_SUFF,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MOTHER_LNAME_PRIOR,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MOTHER_GNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MOTHER_MNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MOTHER_SUFF,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|||||||' + ISNULL(BPLACE_CITY,'') + '||' + ISNULL(BPLACE_ST,'') +'||' + ISNULL(BPLACE_CNT,'') --139 POSITION
+ '||||||||||||||||||||' 
--+ CASE WHEN SIGN_DATE_ME IS NOT NULL THEN CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , SIGN_DATE_ME)),112 ) + '6666'   --CHECK THIS AGAIN
--	   ELSE (CASE WHEN CERT_SIGN_DATE = '99/99/9999' THEN '99999999' + '6666'
--					ELSE CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , CERT_SIGN_DATE)),112 ) + '6666' 
--					END) 
--	   END 
+ CASE  WHEN SIGN_DATE_ME = '99/99/9999' THEN '99999999' + '9999'
	    WHEN SIGN_DATE_ME IS NULL AND CERT_SIGN_DATE IS NULL THEN ''
		WHEN SIGN_DATE_ME IS NOT NULL AND ISDATE(SIGN_DATE_ME) = 1 THEN CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , SIGN_DATE_ME)),112 ) + '6666'   
		WHEN SIGN_DATE_ME IS NOT NULL AND ISDATE(SIGN_DATE_ME) = 0 THEN REPLACE ((RIGHT(SIGN_DATE_ME,4) + LEFT(SIGN_DATE_ME,6)),'/','') + '6666'
		WHEN SIGN_DATE_ME IS NULL AND CERT_SIGN_DATE = '99/99/9999' THEN '999999999999'
		WHEN SIGN_DATE_ME IS NULL AND ISDATE(CERT_SIGN_DATE)=1 THEN CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , CERT_SIGN_DATE)),112 ) + '6666'
		WHEN SIGN_DATE_ME IS NULL AND ISDATE(CERT_SIGN_DATE)=0 THEN REPLACE ((RIGHT(CERT_SIGN_DATE,4) + LEFT(CERT_SIGN_DATE,6)),'/','') + '6666'
		END
+ '|' + CASE WHEN CERT_DESIG = 'CERTIFIER IN ATTENDANCE AT TIME OF DEATH' AND FL_PRONOUNCEMENT_EXISTS = 'Y' THEN 'Certifying Practitioner'
			 WHEN CERT_DESIG = 'CERTIFIER IN ATTENDANCE AT TIME OF DEATH' AND FL_PRONOUNCEMENT_EXISTS = 'N' THEN 'Pronouncing and Certifying Practitioner'
			 WHEN CERT_DESIG = 'MEDICAL EXAMINER' THEN 'Medical Examiner'
			 WHEN CERT_DESIG = 'PHYSICIAN IN CHARGE OF PATIENT''S CARE' AND FL_PRONOUNCEMENT_EXISTS = 'Y' THEN 'Certifying Practitioner'
			 WHEN CERT_DESIG = 'PHYSICIAN IN CHARGE OF PATIENT''S CARE' AND FL_PRONOUNCEMENT_EXISTS = 'N' THEN 'Pronouncing and Certifying Practitioner'
			 WHEN CERT_DESIG = 'NURSE PRACTITIONER IN ATTENDANCE AT THE TIME OF PATIENT''S DEATH' AND FL_PRONOUNCEMENT_EXISTS = 'Y' THEN 'Certifying Practitioner'
			 WHEN CERT_DESIG = 'NURSE PRACTITIONER IN ATTENDANCE AT THE TIME OF PATIENT''S DEATH' AND FL_PRONOUNCEMENT_EXISTS = 'N' THEN 'Pronouncing and Certifying Practitioner'
			 WHEN CERT_DESIG = 'NURSE PRACTITIONER IN CHARGE OF PATIENT''S CARE' AND FL_PRONOUNCEMENT_EXISTS = 'Y' THEN 'Certifying Practitioner'
			 WHEN CERT_DESIG = 'NURSE PRACTITIONER IN CHARGE OF PATIENT''S CARE' AND FL_PRONOUNCEMENT_EXISTS = 'N' THEN 'Pronouncing and Certifying Practitioner'
			 WHEN CERT_DESIG = 'PHYSICIAN ASSISTANT IN ATTENDANCE AT TIME OF DEATH' AND FL_PRONOUNCEMENT_EXISTS = 'Y' THEN 'Certifying Practitioner'
			 WHEN CERT_DESIG = 'PHYSICIAN ASSISTANT IN ATTENDANCE AT TIME OF DEATH' AND FL_PRONOUNCEMENT_EXISTS = 'N' THEN 'Pronouncing and Certifying Practitioner'
			 WHEN CERT_DESIG = 'PHYSICIAN ASSISTANT IN CHARGE OF PATIENT''S CARE' AND FL_PRONOUNCEMENT_EXISTS = 'Y' THEN 'Certifying Practitioner'
			 WHEN CERT_DESIG = 'PHYSICIAN ASSISTANT IN CHARGE OF PATIENT''S CARE' AND FL_PRONOUNCEMENT_EXISTS = 'N' THEN 'Pronouncing and Certifying Practitioner'
 END
+ '|' + ISNULL(CERT_LNAME,'')
+ '|' + ISNULL(CERT_GNAME,'')
+ '|' + ISNULL(CERT_MNAME,'')
+ '|' + ISNULL(CERT_SUFF,'') 
+ '|' + CASE WHEN CERT_TITLE = 1 THEN 'MD'
			WHEN CERT_TITLE = 2 THEN 'DO'
			WHEN CERT_TITLE = 3 THEN 'NP'
			WHEN CERT_TITLE = 4 THEN 'PA'
			WHEN CERT_TITLE = 8 THEN 'Other'
			WHEN CERT_TITLE IS NULL THEN ''
		END
+ '|' + ISNULL(CERT_LIC_NUM,'') + '|' + ISNULL(CERT_ADDR_NUM,'') + '|' + ISNULL(CERT_STREET_PREFIX,'') + '|' + ISNULL(CERT_ADDR1,'') + '|' + ISNULL(CERT_STREET_DESIG,'') 
+ '|' + ISNULL(CERT_STREET_SUFFIX,'') + '|' + ISNULL(CERT_ADDR2,'') + '|' + ISNULL(CERT_CITY,'') + '|' + ISNULL(CERT_STATE,'') + '|' + ISNULL(CERT_ZIPCD,'') + '|' + ISNULL(CERT_CNTRY,'') 
+ '||'+ CASE WHEN INFO_RELATION = 'OTHER' THEN 'Other (Specify)'
			 WHEN INFO_RELATION IS NULL THEN ''
			 ELSE INFO_RELATION
		END
--REPLACE(ISNULL(INFO_RELATION,''),'OTHER','Other (Specify)') 
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(INFO_LST_NME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(INFO_NME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(INFO_MIDD_NME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|' + ISNULL(INFO_SUFFIX,'') 
+ '|' --+ ISNULL(CAST(CAST(REVERSE(INFO_ADDR_NUM) AS INT) AS VARCHAR (20)),'')
+ CASE WHEN INFO_ADDR_NUM LIKE '%,%' THEN '99' 
		WHEN ISNUMERIC(INFO_ADDR_NUM)=1 THEN ISNULL(CAST(CAST(REVERSE(REPLACE(INFO_ADDR_NUM,'.','')) AS INT) AS VARCHAR (20)),'')
	   WHEN INFO_ADDR_NUM IS NULL THEN ''
	   ELSE '99'
  END
+ '|' + ISNULL(INFO_STREET_PREFIX,'') + '|'
--+ CASE WHEN INFO_ADDR1 IS NOT NULL AND INFO_PO_BOX IS NOT NULL

--		THEN INFO_ADDR1 + ' PO BOX' + ISNULL(REPLACE(INFO_PO_BOX,'PO BOX',''),'')
--		WHEN INFO_ADDR1 IS NOT NULL AND INFO_PO_BOX IS NULL
--		THEN INFO_ADDR1
--		WHEN INFO_ADDR1 IS NULL AND INFO_PO_BOX IS NOT NULL
--		THEN 'PO BOX ' + ISNULL(REPLACE(INFO_PO_BOX,'PO BOX',''),'') 
--		ELSE ISNULL(INFO_ADDR1,'') + ISNULL(INFO_PO_BOX,'') END 

+ CASE WHEN INFO_ADDR1 IS NOT NULL AND INFO_PO_BOX IS NOT NULL
		THEN ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(INFO_ADDR1,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
		+ ' PO BOX ' + ISNULL(REPLACE(REPLACE(INFO_PO_BOX,'PO BOX',''),'BOX',''),'')
	 WHEN INFO_ADDR1 IS NOT NULL AND INFO_PO_BOX IS NULL
		THEN ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(INFO_ADDR1,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'') 
	 WHEN INFO_ADDR1 IS NULL AND INFO_PO_BOX IS NOT NULL
		THEN 'PO BOX ' + ISNULL(REPLACE(REPLACE(INFO_PO_BOX,'PO BOX',''),'BOX',''),'') 
	 WHEN INFO_ADDR1 IS NULL AND INFO_PO_BOX IS NULL THEN '' 
		END
+ '|' + ISNULL(INFO_STREET_DESIG,'') +'|' + ISNULL(INFO_STREET_SUFFIX,'') + '|'  + ISNULL(INFO_ADDR2,'') + '|' + ISNULL(INFO_CITY,'') + '|' + ISNULL(INFO_STATE,'') + '|' + ISNULL(INFO_ZIP,'') 
+ '|' + ISNULL(INFO_COUNTRY,'') --192 POSITION 
+ '||||||' 
+ CASE  WHEN AUTOPSY = 'M' THEN 'Yes - ME'
		WHEN AUTOPSY = 'P' THEN 'Yes - Private'
		WHEN AUTOPSY = 'N' THEN 'No'
		WHEN AUTOPSY ='U' THEN 'Unknown' 
		WHEN AUTOPSY IS NULL THEN ''END
+'|' 
+ CASE WHEN AUTOPSY_F_AVAIL = 'Y' THEN 'Yes'
	   WHEN AUTOPSY_F_AVAIL = 'N' THEN 'No'
	   WHEN AUTOPSY_F_AVAIL = 'U' THEN 'Unknown'
	   WHEN AUTOPSY_F_AVAIL IS NULL THEN ''	END 
+ '|' 
+ CASE  WHEN MANNER = 'N' THEN 'Natural'
		WHEN MANNER = 'A' THEN 'Accident'
		WHEN MANNER = 'S' THEN 'Suicide'
		WHEN MANNER = 'H' THEN 'Homicide'
		WHEN MANNER = 'P' THEN 'Pending Investigation'
		WHEN MANNER = 'C' THEN 'Could not be determined'
		WHEN MANNER = 'T' THEN 'Therapeutic complication'
		WHEN MANNER = 'O' THEN 'Other'
		WHEN MANNER IS NULL THEN ''	END
+'|' 
+ CASE  WHEN ME_CR_CONT = 'Y' THEN 'YES'
		WHEN ME_CR_CONT = 'N' THEN 'NO'
		WHEN ME_CR_CONT IS NULL THEN ''		END
+ '|' + ISNULL(ME_CASE_NUM,'') + '||||' 
+ CASE  WHEN PREG = 1 THEN 'Not pregnant within the past year'
		WHEN PREG = 2 THEN 'Pregnant at the time of death'
		WHEN PREG = 3 THEN 'Not pregnant, but pregnant within 42 days of death'
		WHEN PREG = 4 THEN 'Not pregnant, but pregnant 43 days to 1 year before death'
		WHEN PREG = 8 THEN 'Not Applicable'
		WHEN PREG = 9 THEN 'Unknown if pregnant within the last year'
		WHEN PREG IS NULL THEN ''		END
+'|' 
+ CASE  WHEN TOBAC = 'Y' THEN 'Yes' --207
		WHEN TOBAC = 'N' THEN 'No'
		WHEN TOBAC = 'P' THEN 'Probably'
		WHEN TOBAC = 'U' THEN 'Unknown'
		WHEN TOBAC IS NULL THEN ''		END
+'|||||||||||||||||||||||||||'									--IF DISLOCATION ISSUE CHECK THIS DELIMITERS
+ CASE WHEN DISP_DATE IS NULL THEN '' 
		ELSE CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , DISP_DATE)),112 )+ '6666' 
		END 
+ '|' 
+ CASE WHEN DISP = 'B' THEN  'Burial'
		WHEN DISP = 'C' THEN 'Cremation'
		WHEN DISP = 'E' THEN 'Entombment'
		WHEN DISP = 'D' THEN 'Donation'
		WHEN DISP = 'R' THEN 'Removal from State'
		WHEN DISP = 'O' THEN 'Other'
		WHEN DISP = 'U' THEN 'Unknown'
		WHEN DISP IS NULL THEN ''
	END
+ '|' + ISNULL(FDIR_LST_NME,'')
+ '|' + ISNULL(FDIR_FRST_NME,'')
+ '|' + ISNULL(FDIR_MIDD_NME,'')
+ '|' + ISNULL(FDIR_SUFFIX,'') 
+ '|' + ISNULL(FDIR_LIC_NUM,'') 
+ '|' + ISNULL(FNRL_NME,'') + '||' + ISNULL(FNRL_ADDR_NUM,'') + '|' + ISNULL(FNRL_STREET_PREFIX,'') + '|' + ISNULL(FNRL_ADDR1,'') 
+ '|' + ISNULL(FNRL_STREET_DESIG,'') + '|' + ISNULL(FNRL_STREET_SUFFIX,'') 
+ '|' + ISNULL(FNRL_ADDR2,'') + '|' + ISNULL(FNRL_CITY,'') + '|' + ISNULL(FNRL_STATE,'') + '|' + ISNULL(FNRL_ZIPCD,'') + '|' + ISNULL(FNRL_CNTRY,'') 
+ '|' + ISNULL(DISP_NME,'') + '||' + ISNULL(DISP_CTY,'') + '|' + ISNULL(DISP_ST,'') + '|' + ISNULL(DISP_CNTRY,'') + '|' + ISNULL(SFN_NUM_OOS,'') + '|' 
--+ CASE WHEN BURIAL_PERMIT_NONE = 'Y' THEN ''
	--	WHEN BURIAL_PERMIT_NONE = 'N' THEN
	--		(CASE WHEN C.CURRENT_CITY_OPT_IN = 'Y' 
	--			  THEN  ISNULL((CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , BURIAL_PERMIT_ISSUE_DATE )),112 ) + '6666'),(CONVERT(VARCHAR(30),CONVERT (DATETIME , BURIAL_PERMIT_ISSUE_DATE_RV ),112 ) + '6666'))
	--			  ELSE ISNULL((CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , BURIAL_PERMIT_ISSUE_DATE )),112 ) + '6666'),'') 
	--			  END)
	--	END

+ CASE WHEN BURIAL_PERMIT_NONE = 'Y' THEN ''
		WHEN BURIAL_PERMIT_NONE = 'N' THEN
			(CASE WHEN C.CURRENT_CITY_OPT_IN = 'Y' AND BURIAL_PERMIT_ISSUE_DATE IS NULL AND ISDATE(BURIAL_PERMIT_ISSUE_DATE_RV) = 0 
					THEN REPLACE ((RIGHT(BURIAL_PERMIT_ISSUE_DATE,4) + LEFT(BURIAL_PERMIT_ISSUE_DATE,6)),'/','') + '6666'
				  WHEN C.CURRENT_CITY_OPT_IN = 'Y' AND BURIAL_PERMIT_ISSUE_DATE IS NULL AND ISDATE(BURIAL_PERMIT_ISSUE_DATE_RV) = 1 
					THEN (CONVERT(VARCHAR(30),CONVERT (DATETIME , BURIAL_PERMIT_ISSUE_DATE_RV ),112 ) + '6666')
				  WHEN C.CURRENT_CITY_OPT_IN = 'Y' AND ISDATE(BURIAL_PERMIT_ISSUE_DATE) = 0 
					THEN REPLACE ((RIGHT(BURIAL_PERMIT_ISSUE_DATE,4) + LEFT(BURIAL_PERMIT_ISSUE_DATE,6)),'/','') + '6666'
				  WHEN C.CURRENT_CITY_OPT_IN = 'Y' AND ISDATE(BURIAL_PERMIT_ISSUE_DATE) = 1 
					THEN CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , BURIAL_PERMIT_ISSUE_DATE )),112 ) + '6666'
				  WHEN BURIAL_PERMIT_ISSUE_DATE IS NULL AND BURIAL_PERMIT_ISSUE_DATE_RV IS NULL THEN ''
				  WHEN C.CURRENT_CITY_OPT_IN = 'N'
					THEN ISNULL((CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , BURIAL_PERMIT_ISSUE_DATE )),112 ) + '6666'),'') 
				  END)
		--WHEN BURIAL_PERMIT_NONE IS NULL THEN ''
	END
+ '|' 
+  CASE WHEN BURIAL_PERMIT_NONE = 'Y' THEN ''
		WHEN BURIAL_PERMIT_NONE = 'N' AND BURIAL_PERMIT_NUMBER IS NULL AND BURIAL_PERMIT_NUMBER_RV IS NULL THEN ''
		WHEN BURIAL_PERMIT_NONE = 'N' THEN
			(CASE WHEN C.CURRENT_CITY_OPT_IN = 'Y' THEN ISNULL(BURIAL_PERMIT_NUMBER,BURIAL_PERMIT_NUMBER_RV)
				  ELSE ISNULL(BURIAL_PERMIT_NUMBER,'') END)
		
		END
+ '|' + OCCUR_REGIS_NUM + '||||' 
+ CASE WHEN EXP_SSA_DATE_CREATED IS NULL THEN '' 
		ELSE CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , EXP_SSA_DATE_CREATED)),112 ) + '' +
			REPLACE(LEFT(CAST(CONVERT (TIME , EXP_SSA_DATE_CREATED) AS VARCHAR (20)),6),':','') 
		END
+ '|' + ISNULL(BIRTH_SFN_NUM,'') + '|||||||||'
+ ISNULL(RES_COUNTRY_FIPS_CD,'') + '|' + ISNULL(RES_COUNTY_FIPS_CD,'') + '||' + ISNULL(RES_STATE_FIPS_CD,'') + '|||||||||||' + ISNULL(BPLACE_CNT_FIPS_CD,'') + '||||||||||' 
+ 'US' + '|' + ISNULL(DCOUNTY_FIPS_CD,'') + '||' + ISNULL(DSTATEL_FIPS_CD,'') + '||||||||||||||||||||||||||' 
+ CASE WHEN INJRY_PLACEL IN ('Home'
							,'Farm'
							,'Residential Institution'
							,'Military Residence'
							,'Hospital','School, Other Institution, Administrative Area'
							,'Industrial & Construction'
							,'Garage/Warehouse'
							,'Trade and Service Area'
							,'Mine/Quarry'
							,'Street/Highway'
							,'Public Recreation Area'
							,'Institutional recreation Area'
							,'Sports & Athletics Area'
							,'Other building'
							,'Other Specified Place'
							,'Unspecified Place'
							,'Unknown')
		THEN ''
		WHEN INJRY_PLACEL IS NULL THEN ''
		ELSE INJRY_PLACEL END
+ '|' + CASE WHEN LINE1= 1 AND  SEQ1= 1 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 1 AND  SEQ2= 1  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 1 AND  SEQ3= 1 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 1 AND  SEQ4= 1 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 1 AND  SEQ5= 1 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 1 AND  SEQ6= 1 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 1 AND  SEQ7= 1 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 1 AND  SEQ8= 1 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 1 AND  SEQ9= 1 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 1 AND  SEQ10= 1 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 1 AND  SEQ11= 1 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 1 AND  SEQ12= 1 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 1 AND  SEQ13= 1 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 1 AND  SEQ14= 1 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 1 AND  SEQ15= 1 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 1 AND  SEQ16= 1 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 1 AND  SEQ17= 1 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 1 AND  SEQ18= 1 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 1 AND  SEQ19= 1 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 1 AND  SEQ20= 1 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END 
+ '|' + CASE WHEN LINE1= 1  AND  SEQ1= 2 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 1 AND  SEQ2= 2  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 1 AND  SEQ3= 2 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 1 AND  SEQ4= 2 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 1 AND  SEQ5= 2 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 1 AND  SEQ6= 2 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 1 AND  SEQ7= 2 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 1 AND  SEQ8= 2 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 1 AND  SEQ9= 2 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 1 AND  SEQ10= 2 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 1 AND  SEQ11= 2 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 1 AND  SEQ12= 2 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 1 AND  SEQ13= 2 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 1 AND  SEQ14= 2 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 1 AND  SEQ15= 2 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 1 AND  SEQ16= 2 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 1 AND  SEQ17= 2 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 1 AND  SEQ18= 2 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 1 AND  SEQ19= 2 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 1 AND  SEQ20= 2 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END 
+ '|' + CASE WHEN LINE1= 1  AND  SEQ1= 3 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 1 AND  SEQ2= 3  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 1 AND  SEQ3= 3 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 1 AND  SEQ4= 3 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 1 AND  SEQ5= 3 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 1 AND  SEQ6= 3 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 1 AND  SEQ7= 3 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 1 AND  SEQ8= 3 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 1 AND  SEQ9= 3 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 1 AND  SEQ10= 3 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 1 AND  SEQ11= 3 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 1 AND  SEQ12= 3 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 1 AND  SEQ13= 3 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 1 AND  SEQ14= 3 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 1 AND  SEQ15= 3 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 1 AND  SEQ16= 3 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 1 AND  SEQ17= 3 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 1 AND  SEQ18= 3 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 1 AND  SEQ19= 3 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 1 AND  SEQ20= 3 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END 
+ '|' + CASE WHEN LINE1= 1 AND  SEQ1= 4 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 1 AND  SEQ2= 4  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 1 AND  SEQ3= 4 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 1 AND  SEQ4= 4 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 1 AND  SEQ5= 4 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 1 AND  SEQ6= 4 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 1 AND  SEQ7= 4 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 1 AND  SEQ8= 4 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 1 AND  SEQ9= 4 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 1 AND  SEQ10= 4 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 1 AND  SEQ11= 4 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 1 AND  SEQ12= 4 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 1 AND  SEQ13= 4 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 1 AND  SEQ14= 4 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 1 AND  SEQ15= 4 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 1 AND  SEQ16= 4 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 1 AND  SEQ17= 4 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 1 AND  SEQ18= 4 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 1 AND  SEQ19= 4 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 1 AND  SEQ20= 4 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 1 AND  SEQ1= 5 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 1 AND  SEQ2= 5 THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 1 AND  SEQ3= 5 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 1 AND  SEQ4= 5 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 1 AND  SEQ5= 5 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 1 AND  SEQ6= 5 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 1 AND  SEQ7= 5 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 1 AND  SEQ8= 5 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 1 AND  SEQ9= 5 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 1 AND  SEQ10= 5 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 1 AND  SEQ11= 5 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 1 AND  SEQ12= 5 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 1 AND  SEQ13= 5 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 1 AND  SEQ14= 5 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 1 AND  SEQ15= 5 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 1 AND  SEQ16= 5 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 1 AND  SEQ17= 5 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 1 AND  SEQ18= 5 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 1 AND  SEQ19= 5 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 1 AND  SEQ20= 5 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 1  AND  SEQ1= 6 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 1 AND  SEQ2= 6  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 1 AND  SEQ3= 6 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 1 AND  SEQ4= 6 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 1 AND  SEQ5= 6 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 1 AND  SEQ6= 6 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 1 AND  SEQ7= 6 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 1 AND  SEQ8= 6 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 1 AND  SEQ9= 6 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 1 AND  SEQ10= 6 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 1 AND  SEQ11= 6 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 1 AND  SEQ12= 6 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 1 AND  SEQ13= 6 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 1 AND  SEQ14= 6 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 1 AND  SEQ15= 6 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 1 AND  SEQ16= 6 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 1 AND  SEQ17= 6 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 1 AND  SEQ18= 6 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 1 AND  SEQ19= 6 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 1 AND  SEQ20= 6 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 1  AND  SEQ1= 7 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 1 AND  SEQ2= 7  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 1 AND  SEQ3= 7 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 1 AND  SEQ4= 7 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 1 AND  SEQ5= 7 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 1 AND  SEQ6= 7 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 1 AND  SEQ7= 7 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 1 AND  SEQ8= 7 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 1 AND  SEQ9= 7 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 1 AND  SEQ10= 7 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 1 AND  SEQ11= 7 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 1 AND  SEQ12= 7 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 1 AND  SEQ13= 7 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 1 AND  SEQ14= 7 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 1 AND  SEQ15= 7 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 1 AND  SEQ16= 7 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 1 AND  SEQ17= 7 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 1 AND  SEQ18= 7 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 1 AND  SEQ19= 7 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 1 AND  SEQ20= 7 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 1  AND  SEQ1= 8 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 1 AND  SEQ2= 8  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 1 AND  SEQ3= 8 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 1 AND  SEQ4= 8 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 1 AND  SEQ5= 8 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 1 AND  SEQ6= 8 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 1 AND  SEQ7= 8 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 1 AND  SEQ8= 8 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 1 AND  SEQ9= 8 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 1 AND  SEQ10= 8 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 1 AND  SEQ11= 8 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 1 AND  SEQ12= 8 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 1 AND  SEQ13= 8 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 1 AND  SEQ14= 8 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 1 AND  SEQ15= 8 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 1 AND  SEQ16= 8 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 1 AND  SEQ17= 8 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 1 AND  SEQ18= 8 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 1 AND  SEQ19= 8 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 1 AND  SEQ20= 8 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 2  AND  SEQ1= 1 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 2 AND  SEQ2= 1  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 2 AND  SEQ3= 1 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 2 AND  SEQ4= 1 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 2 AND  SEQ5= 1 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 2 AND  SEQ6= 1 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 2 AND  SEQ7= 1 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 2 AND  SEQ8= 1 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 2 AND  SEQ9= 1 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 2 AND  SEQ10= 1 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 2 AND  SEQ11= 1 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 2 AND  SEQ12= 1 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 2 AND  SEQ13= 1 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 2 AND  SEQ14= 1 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 2 AND  SEQ15= 1 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 2 AND  SEQ16= 1 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 2 AND  SEQ17= 1 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 2 AND  SEQ18= 1 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 2 AND  SEQ19= 1 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 2 AND  SEQ20= 1 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 2  AND  SEQ1= 2 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 2 AND  SEQ2= 2  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 2 AND  SEQ3= 2 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 2 AND  SEQ4= 2 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 2 AND  SEQ5= 2 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 2 AND  SEQ6= 2 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 2 AND  SEQ7= 2 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 2 AND  SEQ8= 2 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 2 AND  SEQ9= 2 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 2 AND  SEQ10= 2 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 2 AND  SEQ11= 2 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 2 AND  SEQ12= 2 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 2 AND  SEQ13= 2 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 2 AND  SEQ14= 2 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 2 AND  SEQ15= 2 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 2 AND  SEQ16= 2 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 2 AND  SEQ17= 2 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 2 AND  SEQ18= 2 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 2 AND  SEQ19= 2 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 2 AND  SEQ20= 2 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 2  AND  SEQ1= 3 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 2 AND  SEQ2= 3  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 2 AND  SEQ3= 3 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 2 AND  SEQ4= 3 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 2 AND  SEQ5= 3 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 2 AND  SEQ6= 3 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 2 AND  SEQ7= 3 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 2 AND  SEQ8= 3 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 2 AND  SEQ9= 3 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 2 AND  SEQ10= 3 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 2 AND  SEQ11= 3 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 2 AND  SEQ12= 3 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 2 AND  SEQ13= 3 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 2 AND  SEQ14= 3 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 2 AND  SEQ15= 3 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 2 AND  SEQ16= 3 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 2 AND  SEQ17= 3 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 2 AND  SEQ18= 3 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 2 AND  SEQ19= 3 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 2 AND  SEQ20= 3 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 2  AND  SEQ1= 4 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 2 AND  SEQ2= 4  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 2 AND  SEQ3= 4 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 2 AND  SEQ4= 4 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 2 AND  SEQ5= 4 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 2 AND  SEQ6= 4 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 2 AND  SEQ7= 4 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 2 AND  SEQ8= 4 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 2 AND  SEQ9= 4 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 2 AND  SEQ10= 4 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 2 AND  SEQ11= 4 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 2 AND  SEQ12= 4 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 2 AND  SEQ13= 4 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 2 AND  SEQ14= 4 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 2 AND  SEQ15= 4 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 2 AND  SEQ16= 4 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 2 AND  SEQ17= 4 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 2 AND  SEQ18= 4 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 2 AND  SEQ19= 4 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 2 AND  SEQ20= 4 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 2  AND  SEQ1= 5 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 2 AND  SEQ2= 5  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 2 AND  SEQ3= 5 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 2 AND  SEQ4= 5 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 2 AND  SEQ5= 5 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 2 AND  SEQ6= 5 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 2 AND  SEQ7= 5 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 2 AND  SEQ8= 5 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 2 AND  SEQ9= 5 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 2 AND  SEQ10= 5 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 2 AND  SEQ11= 5 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 2 AND  SEQ12= 5 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 2 AND  SEQ13= 5 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 2 AND  SEQ14= 5 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 2 AND  SEQ15= 5 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 2 AND  SEQ16= 5 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 2 AND  SEQ17= 5 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 2 AND  SEQ18= 5 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 2 AND  SEQ19= 5 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 2 AND  SEQ20= 5 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 2  AND  SEQ1= 6 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 2 AND  SEQ2= 6  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 2 AND  SEQ3= 6 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 2 AND  SEQ4= 6 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 2 AND  SEQ5= 6 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 2 AND  SEQ6= 6 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 2 AND  SEQ7= 6 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 2 AND  SEQ8= 6 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 2 AND  SEQ9= 6 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 2 AND  SEQ10= 6 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 2 AND  SEQ11= 6 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 2 AND  SEQ12= 6 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 2 AND  SEQ13= 6 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 2 AND  SEQ14= 6 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 2 AND  SEQ15= 6 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 2 AND  SEQ16= 6 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 2 AND  SEQ17= 6 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 2 AND  SEQ18= 6 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 2 AND  SEQ19= 6 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 2 AND  SEQ20= 6 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 2  AND  SEQ1= 7 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 2 AND  SEQ2= 7  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 2 AND  SEQ3= 7 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 2 AND  SEQ4= 7 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 2 AND  SEQ5= 7 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 2 AND  SEQ6= 7 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 2 AND  SEQ7= 7 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 2 AND  SEQ8= 7 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 2 AND  SEQ9= 7 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 2 AND  SEQ10= 7 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 2 AND  SEQ11= 7 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 2 AND  SEQ12= 7 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 2 AND  SEQ13= 7 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 2 AND  SEQ14= 7 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 2 AND  SEQ15= 7 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 2 AND  SEQ16= 7 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 2 AND  SEQ17= 7 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 2 AND  SEQ18= 7 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 2 AND  SEQ19= 7 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 2 AND  SEQ20= 7 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 2  AND  SEQ1= 8 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 2 AND  SEQ2= 8  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 2 AND  SEQ3= 8 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 2 AND  SEQ4= 8 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 2 AND  SEQ5= 8 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 2 AND  SEQ6= 8 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 2 AND  SEQ7= 8 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 2 AND  SEQ8= 8 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 2 AND  SEQ9= 8 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 2 AND  SEQ10= 8 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 2 AND  SEQ11= 8 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 2 AND  SEQ12= 8 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 2 AND  SEQ13= 8 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 2 AND  SEQ14= 8 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 2 AND  SEQ15= 8 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 2 AND  SEQ16= 8 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 2 AND  SEQ17= 8 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 2 AND  SEQ18= 8 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 2 AND  SEQ19= 8 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 2 AND  SEQ20= 8 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 3  AND  SEQ1= 1 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 3 AND  SEQ2= 1  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 3 AND  SEQ3= 1 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 3 AND  SEQ4= 1 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 3 AND  SEQ5= 1 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 3 AND  SEQ6= 1 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 3 AND  SEQ7= 1 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 3 AND  SEQ8= 1 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 3 AND  SEQ9= 1 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 3 AND  SEQ10= 1 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 3 AND  SEQ11= 1 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 3 AND  SEQ12= 1 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 3 AND  SEQ13= 1 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 3 AND  SEQ14= 1 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 3 AND  SEQ15= 1 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 3 AND  SEQ16= 1 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 3 AND  SEQ17= 1 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 3 AND  SEQ18= 1 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 3 AND  SEQ19= 1 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 3 AND  SEQ20= 1 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 3  AND  SEQ1= 2 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 3 AND  SEQ2= 2  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 3 AND  SEQ3= 2 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 3 AND  SEQ4= 2 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 3 AND  SEQ5= 2 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 3 AND  SEQ6= 2 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 3 AND  SEQ7= 2 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 3 AND  SEQ8= 2 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 3 AND  SEQ9= 2 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 3 AND  SEQ10= 2 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 3 AND  SEQ11= 2 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 3 AND  SEQ12= 2 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 3 AND  SEQ13= 2 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 3 AND  SEQ14= 2 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 3 AND  SEQ15= 2 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 3 AND  SEQ16= 2 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 3 AND  SEQ17= 2 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 3 AND  SEQ18= 2 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 3 AND  SEQ19= 2 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 3 AND  SEQ20= 2 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 3  AND  SEQ1= 3 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 3 AND  SEQ2= 3  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 3 AND  SEQ3= 3 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 3 AND  SEQ4= 3 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 3 AND  SEQ5= 3 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 3 AND  SEQ6= 3 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 3 AND  SEQ7= 3 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 3 AND  SEQ8= 3 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 3 AND  SEQ9= 3 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 3 AND  SEQ10= 3 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 3 AND  SEQ11= 3 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 3 AND  SEQ12= 3 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 3 AND  SEQ13= 3 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 3 AND  SEQ14= 3 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 3 AND  SEQ15= 3 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 3 AND  SEQ16= 3 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 3 AND  SEQ17= 3 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 3 AND  SEQ18= 3 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 3 AND  SEQ19= 3 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 3 AND  SEQ20= 3 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 3  AND  SEQ1= 4 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 3 AND  SEQ2= 4  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 3 AND  SEQ3= 4 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 3 AND  SEQ4= 4 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 3 AND  SEQ5= 4 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 3 AND  SEQ6= 4 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 3 AND  SEQ7= 4 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 3 AND  SEQ8= 4 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 3 AND  SEQ9= 4 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 3 AND  SEQ10= 4 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 3 AND  SEQ11= 4 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 3 AND  SEQ12= 4 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 3 AND  SEQ13= 4 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 3 AND  SEQ14= 4 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 3 AND  SEQ15= 4 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 3 AND  SEQ16= 4 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 3 AND  SEQ17= 4 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 3 AND  SEQ18= 4 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 3 AND  SEQ19= 4 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 3 AND  SEQ20= 4 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 3  AND  SEQ1= 5 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 3 AND  SEQ2= 5  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 3 AND  SEQ3= 5 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 3 AND  SEQ4= 5 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 3 AND  SEQ5= 5 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 3 AND  SEQ6= 5 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 3 AND  SEQ7= 5 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 3 AND  SEQ8= 5 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 3 AND  SEQ9= 5 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 3 AND  SEQ10= 5 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 3 AND  SEQ11= 5 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 3 AND  SEQ12= 5 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 3 AND  SEQ13= 5 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 3 AND  SEQ14= 5 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 3 AND  SEQ15= 5 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 3 AND  SEQ16= 5 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 3 AND  SEQ17= 5 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 3 AND  SEQ18= 5 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 3 AND  SEQ19= 5 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 3 AND  SEQ20= 5 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 3  AND  SEQ1= 6 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 3 AND  SEQ2= 6  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 3 AND  SEQ3= 6 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 3 AND  SEQ4= 6 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 3 AND  SEQ5= 6 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 3 AND  SEQ6= 6 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 3 AND  SEQ7= 6 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 3 AND  SEQ8= 6 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 3 AND  SEQ9= 6 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 3 AND  SEQ10= 6 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 3 AND  SEQ11= 6 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 3 AND  SEQ12= 6 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 3 AND  SEQ13= 6 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 3 AND  SEQ14= 6 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 3 AND  SEQ15= 6 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 3 AND  SEQ16= 6 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 3 AND  SEQ17= 6 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 3 AND  SEQ18= 6 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 3 AND  SEQ19= 6 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 3 AND  SEQ20= 6 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 3  AND  SEQ1= 7 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 3 AND  SEQ2= 7  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 3 AND  SEQ3= 7 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 3 AND  SEQ4= 7 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 3 AND  SEQ5= 7 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 3 AND  SEQ6= 7 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 3 AND  SEQ7= 7 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 3 AND  SEQ8= 7 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 3 AND  SEQ9= 7 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 3 AND  SEQ10= 7 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 3 AND  SEQ11= 7 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 3 AND  SEQ12= 7 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 3 AND  SEQ13= 7 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 3 AND  SEQ14= 7 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 3 AND  SEQ15= 7 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 3 AND  SEQ16= 7 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 3 AND  SEQ17= 7 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 3 AND  SEQ18= 7 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 3 AND  SEQ19= 7 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 3 AND  SEQ20= 7 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 3  AND  SEQ1= 8 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 3 AND  SEQ2= 8  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 3 AND  SEQ3= 8 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 3 AND  SEQ4= 8 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 3 AND  SEQ5= 8 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 3 AND  SEQ6= 8 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 3 AND  SEQ7= 8 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 3 AND  SEQ8= 8 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 3 AND  SEQ9= 8 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 3 AND  SEQ10= 8 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 3 AND  SEQ11= 8 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 3 AND  SEQ12= 8 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 3 AND  SEQ13= 8 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 3 AND  SEQ14= 8 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 3 AND  SEQ15= 8 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 3 AND  SEQ16= 8 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 3 AND  SEQ17= 8 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 3 AND  SEQ18= 8 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 3 AND  SEQ19= 8 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 3 AND  SEQ20= 8 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 4  AND  SEQ1= 1 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 4 AND  SEQ2= 1  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 4 AND  SEQ3= 1 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 4 AND  SEQ4= 1 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 4 AND  SEQ5= 1 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 4 AND  SEQ6= 1 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 4 AND  SEQ7= 1 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 4 AND  SEQ8= 1 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 4 AND  SEQ9= 1 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 4 AND  SEQ10= 1 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 4 AND  SEQ11= 1 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 4 AND  SEQ12= 1 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 4 AND  SEQ13= 1 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 4 AND  SEQ14= 1 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 4 AND  SEQ15= 1 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 4 AND  SEQ16= 1 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 4 AND  SEQ17= 1 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 4 AND  SEQ18= 1 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 4 AND  SEQ19= 1 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 4 AND  SEQ20= 1 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 4  AND  SEQ1= 2 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 4 AND  SEQ2= 2  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 4 AND  SEQ3= 2 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 4 AND  SEQ4= 2 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 4 AND  SEQ5= 2 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 4 AND  SEQ6= 2 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 4 AND  SEQ7= 2 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 4 AND  SEQ8= 2 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 4 AND  SEQ9= 2 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 4 AND  SEQ10= 2 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 4 AND  SEQ11= 2 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 4 AND  SEQ12= 2 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 4 AND  SEQ13= 2 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 4 AND  SEQ14= 2 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 4 AND  SEQ15= 2 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 4 AND  SEQ16= 2 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 4 AND  SEQ17= 2 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 4 AND  SEQ18= 2 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 4 AND  SEQ19= 2 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 4 AND  SEQ20= 2 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 4  AND  SEQ1= 3 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 4 AND  SEQ2= 3  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 4 AND  SEQ3= 3 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 4 AND  SEQ4= 3 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 4 AND  SEQ5= 3 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 4 AND  SEQ6= 3 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 4 AND  SEQ7= 3 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 4 AND  SEQ8= 3 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 4 AND  SEQ9= 3 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 4 AND  SEQ10= 3 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 4 AND  SEQ11= 3 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 4 AND  SEQ12= 3 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 4 AND  SEQ13= 3 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 4 AND  SEQ14= 3 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 4 AND  SEQ15= 3 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 4 AND  SEQ16= 3 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 4 AND  SEQ17= 3 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 4 AND  SEQ18= 3 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 4 AND  SEQ19= 3 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 4 AND  SEQ20= 3 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 4  AND  SEQ1= 4 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 4 AND  SEQ2= 4  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 4 AND  SEQ3= 4 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 4 AND  SEQ4= 4 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 4 AND  SEQ5= 4 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 4 AND  SEQ6= 4 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 4 AND  SEQ7= 4 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 4 AND  SEQ8= 4 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 4 AND  SEQ9= 4 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 4 AND  SEQ10= 4 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 4 AND  SEQ11= 4 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 4 AND  SEQ12= 4 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 4 AND  SEQ13= 4 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 4 AND  SEQ14= 4 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 4 AND  SEQ15= 4 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 4 AND  SEQ16= 4 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 4 AND  SEQ17= 4 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 4 AND  SEQ18= 4 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 4 AND  SEQ19= 4 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 4 AND  SEQ20= 4 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 4  AND  SEQ1= 5 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 4 AND  SEQ2= 5  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 4 AND  SEQ3= 5 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 4 AND  SEQ4= 5 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 4 AND  SEQ5= 5 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 4 AND  SEQ6= 5 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 4 AND  SEQ7= 5 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 4 AND  SEQ8= 5 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 4 AND  SEQ9= 5 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 4 AND  SEQ10= 5 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 4 AND  SEQ11= 5 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 4 AND  SEQ12= 5 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 4 AND  SEQ13= 5 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 4 AND  SEQ14= 5 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 4 AND  SEQ15= 5 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 4 AND  SEQ16= 5 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 4 AND  SEQ17= 5 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 4 AND  SEQ18= 5 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 4 AND  SEQ19= 5 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 4 AND  SEQ20= 5 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 4  AND  SEQ1= 6 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 4 AND  SEQ2= 6  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 4 AND  SEQ3= 6 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 4 AND  SEQ4= 6 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 4 AND  SEQ5= 6 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 4 AND  SEQ6= 6 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 4 AND  SEQ7= 6 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 4 AND  SEQ8= 6 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 4 AND  SEQ9= 6 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 4 AND  SEQ10= 6 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 4 AND  SEQ11= 6 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 4 AND  SEQ12= 6 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 4 AND  SEQ13= 6 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 4 AND  SEQ14= 6 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 4 AND  SEQ15= 6 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 4 AND  SEQ16= 6 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 4 AND  SEQ17= 6 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 4 AND  SEQ18= 6 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 4 AND  SEQ19= 6 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 4 AND  SEQ20= 6 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 4  AND  SEQ1= 7 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 4 AND  SEQ2= 7  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 4 AND  SEQ3= 7 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 4 AND  SEQ4= 7 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 4 AND  SEQ5= 7 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 4 AND  SEQ6= 7 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 4 AND  SEQ7= 7 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 4 AND  SEQ8= 7 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 4 AND  SEQ9= 7 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 4 AND  SEQ10= 7 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 4 AND  SEQ11= 7 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 4 AND  SEQ12= 7 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 4 AND  SEQ13= 7 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 4 AND  SEQ14= 7 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 4 AND  SEQ15= 7 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 4 AND  SEQ16= 7 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 4 AND  SEQ17= 7 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 4 AND  SEQ18= 7 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 4 AND  SEQ19= 7 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 4 AND  SEQ20= 7 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 4  AND  SEQ1= 8 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 4 AND  SEQ2= 8  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 4 AND  SEQ3= 8 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 4 AND  SEQ4= 8 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 4 AND  SEQ5= 8 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 4 AND  SEQ6= 8 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 4 AND  SEQ7= 8 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 4 AND  SEQ8= 8 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 4 AND  SEQ9= 8 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 4 AND  SEQ10= 8 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 4 AND  SEQ11= 8 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 4 AND  SEQ12= 8 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 4 AND  SEQ13= 8 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 4 AND  SEQ14= 8 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 4 AND  SEQ15= 8 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 4 AND  SEQ16= 8 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 4 AND  SEQ17= 8 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 4 AND  SEQ18= 8 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 4 AND  SEQ19= 8 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 4 AND  SEQ20= 8 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 6  AND  SEQ1= 1 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 6 AND  SEQ2= 1  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 6 AND  SEQ3= 1 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 6 AND  SEQ4= 1 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 6 AND  SEQ5= 1 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 6 AND  SEQ6= 1 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 6 AND  SEQ7= 1 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 6 AND  SEQ8= 1 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 6 AND  SEQ9= 1 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 6 AND  SEQ10= 1 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 6 AND  SEQ11= 1 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 6 AND  SEQ12= 1 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 6 AND  SEQ13= 1 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 6 AND  SEQ14= 1 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 6 AND  SEQ15= 1 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 6 AND  SEQ16= 1 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 6 AND  SEQ17= 1 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 6 AND  SEQ18= 1 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 6 AND  SEQ19= 1 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 6 AND  SEQ20= 1 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 6  AND  SEQ1= 2 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 6 AND  SEQ2= 2  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 6 AND  SEQ3= 2 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 6 AND  SEQ4= 2 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 6 AND  SEQ5= 2 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 6 AND  SEQ6= 2 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 6 AND  SEQ7= 2 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 6 AND  SEQ8= 2 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 6 AND  SEQ9= 2 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 6 AND  SEQ10= 2 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 6 AND  SEQ11= 2 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 6 AND  SEQ12= 2 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 6 AND  SEQ13= 2 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 6 AND  SEQ14= 2 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 6 AND  SEQ15= 2 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 6 AND  SEQ16= 2 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 6 AND  SEQ17= 2 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 6 AND  SEQ18= 2 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 6 AND  SEQ19= 2 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 6 AND  SEQ20= 2 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 6  AND  SEQ1= 3 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 6 AND  SEQ2= 3  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 6 AND  SEQ3= 3 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 6 AND  SEQ4= 3 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 6 AND  SEQ5= 3 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 6 AND  SEQ6= 3 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 6 AND  SEQ7= 3 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 6 AND  SEQ8= 3 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 6 AND  SEQ9= 3 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 6 AND  SEQ10= 3 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 6 AND  SEQ11= 3 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 6 AND  SEQ12= 3 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 6 AND  SEQ13= 3 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 6 AND  SEQ14= 3 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 6 AND  SEQ15= 3 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 6 AND  SEQ16= 3 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 6 AND  SEQ17= 3 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 6 AND  SEQ18= 3 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 6 AND  SEQ19= 3 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 6 AND  SEQ20= 3 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 6  AND  SEQ1= 4 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 6 AND  SEQ2= 4  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 6 AND  SEQ3= 4 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 6 AND  SEQ4= 4 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 6 AND  SEQ5= 4 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 6 AND  SEQ6= 4 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 6 AND  SEQ7= 4 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 6 AND  SEQ8= 4 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 6 AND  SEQ9= 4 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 6 AND  SEQ10= 4 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 6 AND  SEQ11= 4 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 6 AND  SEQ12= 4 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 6 AND  SEQ13= 4 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 6 AND  SEQ14= 4 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 6 AND  SEQ15= 4 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 6 AND  SEQ16= 4 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 6 AND  SEQ17= 4 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 6 AND  SEQ18= 4 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 6 AND  SEQ19= 4 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 6 AND  SEQ20= 4 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 6  AND  SEQ1= 5 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 6 AND  SEQ2= 5  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 6 AND  SEQ3= 5 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 6 AND  SEQ4= 5 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 6 AND  SEQ5= 5 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 6 AND  SEQ6= 5 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 6 AND  SEQ7= 5 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 6 AND  SEQ8= 5 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 6 AND  SEQ9= 5 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 6 AND  SEQ10= 5 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 6 AND  SEQ11= 5 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 6 AND  SEQ12= 5 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 6 AND  SEQ13= 5 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 6 AND  SEQ14= 5 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 6 AND  SEQ15= 5 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 6 AND  SEQ16= 5 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 6 AND  SEQ17= 5 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 6 AND  SEQ18= 5 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 6 AND  SEQ19= 5 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 6 AND  SEQ20= 5 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 6  AND  SEQ1= 6 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 6 AND  SEQ2= 6  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 6 AND  SEQ3= 6 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 6 AND  SEQ4= 6 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 6 AND  SEQ5= 6 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 6 AND  SEQ6= 6 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 6 AND  SEQ7= 6 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 6 AND  SEQ8= 6 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 6 AND  SEQ9= 6 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 6 AND  SEQ10= 6 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 6 AND  SEQ11= 6 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 6 AND  SEQ12= 6 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 6 AND  SEQ13= 6 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 6 AND  SEQ14= 6 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 6 AND  SEQ15= 6 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 6 AND  SEQ16= 6 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 6 AND  SEQ17= 6 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 6 AND  SEQ18= 6 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 6 AND  SEQ19= 6 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 6 AND  SEQ20= 6 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 6  AND  SEQ1= 7 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 6 AND  SEQ2= 7  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 6 AND  SEQ3= 7 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 6 AND  SEQ4= 7 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 6 AND  SEQ5= 7 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 6 AND  SEQ6= 7 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 6 AND  SEQ7= 7 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 6 AND  SEQ8= 7 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 6 AND  SEQ9= 7 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 6 AND  SEQ10= 7 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 6 AND  SEQ11= 7 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 6 AND  SEQ12= 7 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 6 AND  SEQ13= 7 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 6 AND  SEQ14= 7 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 6 AND  SEQ15= 7 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 6 AND  SEQ16= 7 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 6 AND  SEQ17= 7 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 6 AND  SEQ18= 7 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 6 AND  SEQ19= 7 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 6 AND  SEQ20= 7 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '|' + CASE WHEN LINE1= 6  AND  SEQ1= 8 THEN ISNULL(CAUSE_CATEGORY1,'')
			 WHEN LINE2= 6 AND  SEQ2= 8  THEN ISNULL(CAUSE_CATEGORY2,'')
			 WHEN LINE3= 6 AND  SEQ3= 8 THEN ISNULL(CAUSE_CATEGORY3,'')
			 WHEN LINE4= 6 AND  SEQ4= 8 THEN ISNULL(CAUSE_CATEGORY4,'')
			 WHEN LINE5= 6 AND  SEQ5= 8 THEN ISNULL(CAUSE_CATEGORY5,'')
			 WHEN LINE6= 6 AND  SEQ6= 8 THEN ISNULL(CAUSE_CATEGORY6,'')
			 WHEN LINE7= 6 AND  SEQ7= 8 THEN ISNULL(CAUSE_CATEGORY7,'')
			 WHEN LINE8= 6 AND  SEQ8= 8 THEN ISNULL(CAUSE_CATEGORY8,'')
			 WHEN LINE9= 6 AND  SEQ9= 8 THEN ISNULL(CAUSE_CATEGORY9,'')
			 WHEN LINE10= 6 AND  SEQ10= 8 THEN ISNULL(CAUSE_CATEGORY10,'')
			 WHEN LINE11= 6 AND  SEQ11= 8 THEN ISNULL(CAUSE_CATEGORY11,'')
			 WHEN LINE12= 6 AND  SEQ12= 8 THEN ISNULL(CAUSE_CATEGORY12,'')
			 WHEN LINE13= 6 AND  SEQ13= 8 THEN ISNULL(CAUSE_CATEGORY13,'')
			 WHEN LINE14= 6 AND  SEQ14= 8 THEN ISNULL(CAUSE_CATEGORY14,'')
			 WHEN LINE15= 6 AND  SEQ15= 8 THEN ISNULL(CAUSE_CATEGORY15,'')
			 WHEN LINE16= 6 AND  SEQ16= 8 THEN ISNULL(CAUSE_CATEGORY16,'')
			 WHEN LINE17= 6 AND  SEQ17= 8 THEN ISNULL(CAUSE_CATEGORY17,'')
			 WHEN LINE18= 6 AND  SEQ18= 8 THEN ISNULL(CAUSE_CATEGORY18,'')
			 WHEN LINE19= 6 AND  SEQ19= 8 THEN ISNULL(CAUSE_CATEGORY19,'')
			 WHEN LINE20= 6 AND  SEQ20= 8 THEN ISNULL(CAUSE_CATEGORY20,'')
			 ELSE ''
		END
+ '||||||||||||||' + ISNULL(TRX_CAUSE_MANUAL,'') 
+ '|'  + ISNULL(CODIA,'') +'|' + ISNULL(INTIA,'') +'|' + REPLACE(ISNULL(CODIB,''),'|',' ') +'|' + ISNULL(INTIB,'') +'|' + ISNULL(CODIC,'') +'|' + ISNULL(INTIC,'') +'|' + ISNULL(CODID,'') +'|' + ISNULL(INTID,'') 
+ '|' + REPLACE(REPLACE(REPLACE(ISNULL(CONDII,''),CHAR(13),SPACE(1)),CHAR(10),SPACE(1)),'|','  ') + '||' + REPLACE(REPLACE(ISNULL(INJRY_L,''),CHAR(13),SPACE(0)),CHAR(10),SPACE(0)) +--+ ISNULL(INJRY_L,'') 
+ '|' 
+ CASE WHEN INJRY_WORK = 'Y' THEN 'Yes'
		WHEN INJRY_WORK = 'N' THEN 'No'
		WHEN INJRY_WORK = 'U' THEN 'Unknown'
		WHEN INJRY_WORK IS NULL THEN ''
	END
+ '|' 
--+ CASE WHEN DOI = '99/99/9999' THEN '' 
--  ELSE ISNULL(CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME, DOI)),112),'') END
--+ REPLACE(ISNULL(TOI,''),':','') 
+ CASE WHEN DOI = '99/99/9999' THEN ''
	   WHEN DOI IS NULL THEN ''
	   WHEN ISDATE(DOI)= 0 THEN  REPLACE ((RIGHT(DOI,4) + LEFT(DOI,6)),'/','') + REPLACE(ISNULL(TOI,'6666'),':','') 
	   WHEN ISDATE(DOI) = 1 THEN ISNULL(CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME, DOI)),112),'')  + REPLACE(ISNULL(TOI,'6666'),':','')
  END
+ '|' + CASE WHEN INJRY_PLACEL IN ('Home'
								,'Farm'
								,'Residential Institution'
								,'Military Residence'
								,'Hospital'
								,'School, Other Institution, Administrative Area'
								,'Industrial & Construction'
								,'Garage/Warehouse'
								,'Trade and Service Area'
								,'Mine/Quarry'
								,'Street/Highway','Public Recreation Area'
								,'Institutional recreation Area'
								,'Sports & Athletics Area'
								,'Other building'
								,'Other Specified Place'
								,'Unspecified Place'
								,'Unknown')
			THEN INJRY_PLACEL 
			WHEN INJRY_PLACEL IS NULL THEN ''
			ELSE 'Other Specified Place' END
+ '|' + ISNULL(INJRY_TRANSPRT,'') + '||' + ISNULL(INJRY_ADDR_NUM,'') + '|' + ISNULL(INJRY_STREET_PREFIX,'') + '|' + ISNULL(INJRY_ADDR1,'') + '|' + ISNULL(INJRY_STREET_DESIG,'') 
+ '|' + ISNULL(INJRY_STREET_SUFFIX,'') + '|' + ISNULL(INJRY_ADDR2,'') + '|' + ISNULL(INJRY_CITY,'') + '||' + ISNULL(INJRY_STATE,'') + '|' + ISNULL(INJRY_ZIP9,'') 
+ '|' + ISNULL(INJRY_COUNTRY,'') 
+ '|' + CONVERT (VARCHAR(8), DATEADD(DAY,+2,CONVERT(DATETIME, VRV_DATE_CHANGED)),112) + '' + REPLACE(LEFT(CAST(CONVERT (TIME , VRV_DATE_CHANGED) AS VARCHAR (20)),6),':','')
+ '|Registered||||||||REGISTERED|||||||||||||||||'
+ CASE WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ',''))=0
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||||||||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 1
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||||||||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 2
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||||||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 3
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||||||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 4
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 5
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 6
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 7
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 8
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 9
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 10
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 11
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 12
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 13
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 14
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 15
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 16
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 17
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 18
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '||'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 19
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + '|'
			WHEN LEN(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' ')) - LEN(REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','')) = 20
			THEN REPLACE(REPLACE(REPLACE(REPLACE(TRX_REC_AXIS_CD,SPACE(4),' '),SPACE(3),' '),SPACE(2),' '),' ','|') + ''
			WHEN TRX_REC_AXIS_CD IS NULL
			THEN '||||||||||||||||||||'
			END
+ ISNULL(TRX_CAUSE_ACME,'') + '|'					--IF SOMETHING LOOK WRONG IN PLACEMENT THEN ADD 20 '|'
+ CASE WHEN SFN_NUM LIKE '2%' THEN 'Hybrid'
		ELSE 'Electronic' 
		END 
+ '|' 
+ CASE WHEN VRV_RECORD_TYPE_ID = '049' THEN '1'
	WHEN VRV_RECORD_TYPE_ID = '040' THEN '0'
	END 
+ '||||||||0|' 
--+ CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME, DOB)),112) +'6666'
+ CASE  WHEN DOB LIKE '99/99/9999' THEN '999999999999'					
		WHEN ISDATE(DOB)= 1 THEN CONVERT (VARCHAR(8),DATEADD(DAY,+2,CONVERT(DATETIME, DOB)),112) + '6666' 
		WHEN ISDATE(DOB)= 0 THEN REPLACE ((RIGHT(DOB,4) + LEFT(DOB,6)),'/','') + '6666' 
		END
+ '||||' + ISNULL(INJRY_TRANSPRT_OTHER,'') + '||||||||||||||||||||' 
+ ISNULL(DNAME_CITY,'') + '|' + ISNULL(INFO_RELATION_OTHER,'') + '|' + ISNULL(DISPL,'') + '||' + ISNULL(DPLACE_OTHR,'') +'||' 
--+ CASE WHEN CREM_CLEAR_ME = 'Y' THEN 'YES'
--		WHEN CREM_CLEAR_ME = 'N' THEN 'NO'
--		WHEN CREM_CLEAR_ME IS NULL THEN ''
--	END
+ '|' + ISNULL(RECORD_REGISTRAR,'') + '|||' 
+ CASE WHEN TOI_IND = 'A' THEN 'AM'
		WHEN TOI_IND = 'P' THEN 'PM'
		WHEN TOI_IND = 'M' THEN 'Military'
		WHEN TOI_IND = 'U' THEN 'Unknown'
		WHEN TOI_IND IS NOT NULL AND TOI = '99:99' THEN ''		
		WHEN TOI_IND IS NULL THEN ''		
		WHEN TOI = '12:00' AND TOI_IND = 'D' THEN 'AM'
		WHEN TOI = '12:00' AND TOI_IND = 'N' THEN 'PM'
		WHEN TOI = '99:99' THEN ''

  END
+ '|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||'
+ ISNULL(DISP_ADDR_NUM,'') + '|' + ISNULL(DISP_STREET_PREFIX,'') + '|' + ISNULL(DISP_ADDR1,'') + '|' + ISNULL(DISP_STREET_DESIG,'') + '|' + ISNULL(DISP_STREET_SUFFIX,'') + '|' 
+ ISNULL(DISP_ADDR2,'') + '||' + ISNULL (DISP_ZIP,'') 
+ '||||||||||||||||||||||||||' + ISNULL(FH_RESPONSIBLE_NAME,'') + '||||'
+ ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MOTHER_LNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'') + '||||'
+ ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SPOUSE_LNAME,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
+ '|||||||||||||||||||' +  ISNULL(CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME, OCCUR_REGIS_DATE)),112),'') + '6666' +'|||||||||||||||') AS DAVEFILEOUT 
FROM [DAVE_MIGRATION].[VIP_VRV_Death_Tbl] D
LEFT JOIN [DAVE_MIGRATION].[VIP_VT_CURRENT_MA_City_CD] C ON D.DCITY_LOC_ID = C.CURRENT_CLERK_LOC_ID 
WHERE VRV_REGISTERED_FLAG =1
AND VRV_RECORD_TYPE_ID = '040'
AND FL_CURRENT =1
AND FL_VOIDED=0
AND ISDATE(DOD)=1
AND (DOD LIKE '%2018') 
ORDER BY DEATH_REC_ID 

--death_rec_id in (2650,663882,156711,184318,186234,179733,181832,427971,33176,84110,435920,113164,624837,439651,545666)
--SELECT * FROM  #TEMP WHERE DAVEFILEOUT IS NULL

