--drop table [RVRS].[Location]
--sp_help '[RVRS].[Location]'
SET ANSI_NULLS ON
GO
 
 
SET QUOTED_IDENTIFIER ON
GO
 
 
IF NOT EXISTS (SELECT 1 FROM sys.Objects 
                WHERE object_id = OBJECT_ID('[RVRS].[Location]') )
	BEGIN
		CREATE TABLE[RVRS].[Location](  		
			[LocationId] BIGINT NOT NULL IDENTITY (1,1),--  RVRS Column 
			[PersonId] BIGINT NOT NULL,  --  RVRS Column 			[DimLocationTypeInternalId] INT NOT NULL CONSTRAINT [df_LocationDimDimLocationTypeInternalId] DEFAULT (0),			[DimLocationId] INT NOT NULL CONSTRAINT [df_LocationDimLocationId] DEFAULT (0), -- ID_NUM_4_OCME,FH_UPDATE_LOC_ID,VRV_FILED_LOCATION_ID,PH_UPDATE_LOC_ID,RES_CITY_LOC_ID,RES_CITY_BA_LOC_ID, VRV_FUNERAL_HOME_LOC_ID,DCITY_LOC_ID,DFAC_LOC_ID,BA_USER_TOWN_LOCATION_ID, NP_ASSOCIATED_PHYSICIAN_LOC_ID,VRV_MC_LOCATION_ID,TRANSFER_DR_LOC_ID,TRANSFER_FH_LOC_ID,START_RECORD_LOC_ID			[CreatedDate] DATETIME NOT NULL CONSTRAINT [df_LocationCreatedDate] DEFAULT (GETDATE()), -- RVRS Column to store created date
		   	[LoadNote] VARCHAR(MAX)
		CONSTRAINT [pk_LocationId] PRIMARY KEY CLUSTERED 
		(
			[LocationId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END
	
	GO 