--drop table [RVRS].[DeathExport]
--sp_help '[RVRS].[DeathExport]'
SET ANSI_NULLS ON
GO
 
 
SET QUOTED_IDENTIFIER ON
GO
 
 
IF NOT EXISTS (SELECT 1 FROM sys.Objects 
                WHERE object_id = OBJECT_ID('[RVRS].[DeathExport]') )
	BEGIN
		CREATE TABLE[RVRS].[DeathExport](  		
			[DeathExportId] BIGINT NOT NULL IDENTITY (1,1),--  RVRS Column 
			[PersonId] BIGINT NOT NULL,  --  RVRS Column 			[AgeType]  DECIMAL(2,0) NULL, -- AGETYPE4EXPORTS			[MaritalStatus]  DECIMAL(2,0) NULL, -- MARITAL4EXPORTS			[Education]  DECIMAL(2,0) NULL, -- EDUC_4_EXPORTS			[Ethnicity1]  VARCHAR(2) NULL, -- DETHNIC1_4_EXPORTS)			[Ethnicity2]  VARCHAR(2) NULL, -- DETHNIC2_4_EXPORTS			[Ethnicity3]  VARCHAR(2) NULL, -- DETHNIC3_4_EXPORTS			[Ethnicity4]  VARCHAR(2) NULL, -- DETHNIC4_4_EXPORTS			[Ethnicity5]  VARCHAR(32) NULL, -- DETHNIC5_4_EXPORTS			[Race1]  VARCHAR(2) NULL, -- RACE1_4_EXPORTS			[Race2]  VARCHAR(2) NULL, -- RACE2_4_EXPORTS			[Race3]  VARCHAR(2) NULL, -- RACE3_4_EXPORT			[Race10]  VARCHAR(2) NULL, -- RACE10_4_EXPORTS			[Race14]  VARCHAR(2) NULL, -- RACE14_4_EXPORTS			[Race15]  VARCHAR(2) NULL, -- RACE15_4_EXPORTS			[Race16]  VARCHAR(32) NULL, -- RACE16_4_EXPORTS			[Race17]  VARCHAR(32) NULL, -- RACE17_4_EXPORTS			[Race18]  VARCHAR(32) NULL, -- RACE18_4_EXPORTS			[Race19]  VARCHAR(32) NULL, -- RACE19_4_EXPORTS			[Race20]  VARCHAR(32) NULL, -- RACE20_4_EXPORTS			[Race21]  VARCHAR(32) NULL, -- RACE21_4_EXPORTS			[Race22]  VARCHAR(32) NULL, -- RACE22_4_EXPORTS			[Race23]  VARCHAR(32) NULL, -- RACE23_4_EXPORTS			[AnotherRace1]  VARCHAR(64) NULL, -- ANOTHER_RACE1			[AutoSpy]  VARCHAR(2) NULL, -- AUTOSPY4EXPORT			[AutoSpyFinding]  VARCHAR(2) NULL, -- AUTOPSY_F_AVAIL4EXPORT			[TransportationInjury]  VARCHAR(64) NULL, -- INJRY_TRANSPRT_EXPORT			[CertifierDesignation]  VARCHAR(32) NULL, -- CERT_DESIG4EXPORT			[DeathTime]  VARCHAR(5) NULL, -- TOD_4_EXPORTS			[DeathTimeInd]  VARCHAR(1) NULL, -- TOD_IN_4_EXPORTS
			[CreatedDate] DATETIME NOT NULL CONSTRAINT [df_DeathExportCreatedDate] DEFAULT (GETDATE()), -- RVRS Column to store created date
		   	[LoadNote] VARCHAR(MAX)
		CONSTRAINT [pk_DeathExportId] PRIMARY KEY CLUSTERED 
		(
			[DeathExportId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END
	
	GO 
