--drop table [RVRS].[OtherDate]
--sp_help '[RVRS].[OtherDate]'
 
 
IF NOT EXISTS (SELECT 1 FROM sys.Objects 
                WHERE object_id = OBJECT_ID('[RVRS].[OtherDate]') )
	BEGIN
		CREATE TABLE[RVRS].[OtherDate](  		
			[OtherDateId] BIGINT NOT NULL IDENTITY (1,1),--  RVRS Column 
			[PersonId] BIGINT NOT NULL,  --  RVRS Column 
			[ActionDate] DATETIME NOT NULL, -- EXP_SSA_DATE_CREATED CERT_SIGN_DATE CERT_VERIFY_DATE SIGN_DATE_ME RELEASE_TO_RVRS_DATE RELEASE_TO_CLERK_DATE STEVE_FIRST_SENT_DATE STEVE_SENT_DATE DATE_DATA_SENT_TO_DOR DATE_IMAGE_SENT_TO_DOR BATCH_PRINTED_DATE
			[DimDateTypeId] INT NOT NULL CONSTRAINT [df_OtherDateDimDateTypeId] DEFAULT (0), -- SEED
			[DimRecordActionId] INT NOT NULL CONSTRAINT [df_OtherDateDimRecordActionId] DEFAULT (0), -- SEED
			[CreatedDate] DATETIME NOT NULL CONSTRAINT [df_OtherDateCreatedDate] DEFAULT (GETDATE()), -- RVRS Column to store created date
		   	[LoadNote] VARCHAR(MAX)
		CONSTRAINT [pk_OtherDateId] PRIMARY KEY CLUSTERED 
		(
			[OtherDateId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END
	
	GO 