--drop table [RVRS].[SystemFlag]
--sp_help '[RVRS].[SystemFlag]'
SET ANSI_NULLS ON
GO
 
 
SET QUOTED_IDENTIFIER ON
GO
 
 
IF NOT EXISTS (SELECT 1 FROM sys.Objects 
                WHERE object_id = OBJECT_ID('[RVRS].[SystemFlag]') )
	BEGIN
		CREATE TABLE[RVRS].[SystemFlag](  		
			[SystemFlagId] BIGINT NOT NULL IDENTITY (1,1),--  RVRS Column 
			[PersonId] BIGINT NOT NULL,  --  RVRS Column 
			[Value] DECIMAL(1,0) NOT NULL, -- MNAME_NONE,SEX_BYPASS, AGE_BYPASS,FL_PRONOUNCEMENT_EXISTS,FL_SEX_COD,FL_ENTERED_FROM_PAPER, FL_AKA_EXIST ,FL_AKA2_EXIST,FL_AKA3_EXIST,AKA4_EXIST, MARITAL_BYPASS
								          -- SPOUSE_NAME_UNK,FATHER_NME_UNK,MOTHER_NME_UNK,DEDUC_BYPASS,INFO_MNAME_NONE,FL_FUNERAL_HOME_UNLISTED
				                          -- TRADE_FH_UNLISTED,FL_FD_UNLISTED,FDIR_OTHER_DESIG,CREM_CEM_UNLISTED, MC_NOTIFIED_UNLISTED, PRO_MNAME_NONE
										  -- ME_MNAME_NONE,DFACILITY_UNLISTED, PREG_BYPASS,INJRY_ADDR_UNK,FL_CERT_UNLISTED,FL_UPDATE_CERT_INFO,ATTEND_PHYSICIAN_UNLISTED
										  -- ATTEND_PHYSICIAN_NONE,ATTEND_PHYSICIAN_MNAME_NONE,DATE_QUAL_ABOUT, IND_MEDICAL_EXCEPTIONS, VERIFY_FORM_NONE,IND_DEMOGRAPHIC_EXCEPTIONS, FL_COD_INJURY, FL_LEGACY_RECORD
										  -- FL_OOC_RECORD, FL_PRESUMPTIVE, ME_SELECTED,VRV_MRE_CODED_FL
			[DimSystemFlagId] INT NOT NULL CONSTRAINT [df_SystemFlagDimSystemFlagId] DEFAULT (0), -- No Column
			[CreatedDate] DATETIME NOT NULL CONSTRAINT [df_SystemFlagCreatedDate] DEFAULT (GETDATE()), -- RVRS Column to store created date
		   	[LoadNote] VARCHAR(MAX)
		CONSTRAINT [pk_SystemFlagId] PRIMARY KEY CLUSTERED 
		(
			[SystemFlagId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END
	
	GO 