--drop table [RVRS].[DimWar]
-- sp_help '[RVRS].[DimWar]'
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT 1 FROM sys.Objects 
					WHERE object_id = OBJECT_ID('[RVRS].[DimWar]') )
	BEGIN 
		CREATE TABLE [RVRS].[DimWar](
			[DimWarId] INT NOT NULL IDENTITY (1,1),	
			[BkWarId] INT NOT NULL,
			[WarDesc] VARCHAR(128) NOT NULL,  
			[StartDate] DateTime NULL,
			[EndDate] DateTime NULL,
			[Void] TINYINT NOT NULL CONSTRAINT [df_DimWarVoid] DEFAULT (0),			
		CONSTRAINT [pk_DimWarId] PRIMARY KEY CLUSTERED 
		(
			[DimWarId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END 
GO


