--drop table [RVRS].[DimPrefix]
--sp_help '[RVRS].[DimPrefix]'
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT 1 FROM sys.Objects 
					WHERE object_id = OBJECT_ID('[RVRS].[DimPrefix]') )
	BEGIN 
		CREATE TABLE [RVRS].[DimPrefix](
			[DimPrefixId] INT NOT NULL IDENTITY (1,1),	
			[BkPrefixId] INT NOT NULL, 
			[Code] DECIMAL(2,0) NOT NULL,	
		    [PrefixDesc] VARCHAR(128) NOT NULL,
			[StartDate] DateTime NULL,
			[EndDate] DateTime NULL,
			[SrcVoid] TINYINT NOT NULL, 
		CONSTRAINT [pk_DimPrefixId] PRIMARY KEY CLUSTERED 
		(
			[DimPrefixId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END 
GO


