--drop table [RVRS].[DimPersonType]
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT 1 FROM sys.Objects 
					WHERE object_id = OBJECT_ID('[RVRS].[DimPersonType]') )
	BEGIN 
		CREATE TABLE [RVRS].[DimPersonType](
			[DimPersonTypeId] INT NOT NULL,		
		    [PersonTypeDesc] VARCHAR(128) NOT NULL,	
			[PersonGuidCode] CHAR(3) NOT NULL,	
			[Void] TINYINT NOT NULL, 
		CONSTRAINT [pk_DimPersonTypeId] PRIMARY KEY CLUSTERED 
		(
			[DimPersonTypeId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END 
GO

