--drop table [RVRS].[DimSuffix]
--sp_help '[RVRS].[DimSuffix]'
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT 1 FROM sys.Objects 
					WHERE object_id = OBJECT_ID('[RVRS].[DimSuffix]') )
	BEGIN 
		CREATE TABLE [RVRS].[DimSuffix](
			[DimSuffixId] INT NOT NULL IDENTITY (1,1),	
			[BkSuffixId] INT NOT NULL, 
			[Code] DECIMAL(2,0) NOT NULL,	
		    [SuffixDesc] VARCHAR(128) NOT NULL,  --'NULL' 
			[StartDate] DateTime NULL,
			[EndDate] DateTime NULL,
			[SrcVoid] TINYINT NOT NULL, 
		CONSTRAINT [pk_DimSuffixId] PRIMARY KEY CLUSTERED 
		(
			[DimSuffixId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END 
GO


