--drop table [RVRS].[DimCaseAccess]
-- sp_help '[RVRS].[DimCaseAccess]'
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT 1 FROM sys.Objects 
					WHERE object_id = OBJECT_ID('[RVRS].[DimCaseAccess]') )
	BEGIN 
		CREATE TABLE [RVRS].[DimCaseAccess](
			[DimCaseAccessId] INT NOT NULL IDENTITY (1,1),			
			[CaseAccessDesc] VARCHAR(128) NOT NULL,  --FAX SERVER,ELECTRONIC
			[StartDate] DateTime NULL,
			[EndDate] DateTime NULL,
			[Void] TINYINT NOT NULL CONSTRAINT [df_DimCaseAccessVoid] DEFAULT (0),			
		CONSTRAINT [pk_DimCaseAccessId] PRIMARY KEY CLUSTERED 
		(
			[DimCaseAccessId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END 
GO


