--drop table [RVRS].[HcProvider]
--sp_help '[RVRS].[HcProvider]'
SET ANSI_NULLS ON
GO
 
 
SET QUOTED_IDENTIFIER ON
GO
 
 
IF NOT EXISTS (SELECT 1 FROM sys.Objects 
                WHERE object_id = OBJECT_ID('[RVRS].[HcProvider]') )
	BEGIN
		CREATE TABLE[RVRS].[HcProvider](  		
			[HcProviderId] BIGINT NOT NULL IDENTITY (1,1),--  RVRS Column 
			[PersonId] BIGINT NOT NULL,  --  RVRS Column 
			[DimPhysicianTypeInternalId] INT NOT NULL CONSTRAINT [df_HcProviderDimPhysicianTypeInternalId] DEFAULT (0),
			[DimPhysicianTitleId] INT NOT NULL CONSTRAINT [df_HcProviderDimPhysicianTitleId] DEFAULT (0), -- CERT_TITLE, PRO_TITLE
			[DimPhysicianId] INT NOT NULL CONSTRAINT [df_HcProviderDimPhysicianId] DEFAULT (0), -- CERT_GNAME,CERT_MNAME,CERT_LNAMECERT_SUFF,CERT_LIC_NUM,ATTEND_PHYSICIAN_GNAME,MC_NOTIFIED_GNAME,ATTEND_PHYSICIAN_MNAME,MC_NOTIFIED_MNAME,ATTEND_PHYSICIAN_LNAME,MC_NOTIFIED_LNAME,ATTEND_PHYSICIAN_SUFFIX,MC_NOTIFIED_SUFFIX,PRO_GNAME,PRO_MNAME,PRO_LNAME,PRO_SUFFIX,PRO_LIC_NUM
			[DimPhoneId] INT NOT NULL CONSTRAINT [df_HcProviderDimPhoneId] DEFAULT (0), -- CERT_CONTACT
			[DimFaxId] INT NOT NULL CONSTRAINT [df_HcProviderDimFaxId] DEFAULT (0), -- CERT_CONTACT_INFO		
			[DimCaseAccessId] INT NOT NULL CONSTRAINT [df_HcProviderDimCaseAccessId] DEFAULT (0), -- CERT_CASE_ACCESS
			[DimEmployerId] INT NOT NULL CONSTRAINT [df_HcProviderDimEmployerId] DEFAULT (0), -- PRO_EMPLOYER
			[CreatedDate] DATETIME NOT NULL CONSTRAINT [df_HcProviderCreatedDate] DEFAULT (GETDATE()), -- RVRS Column to store created date
		   	[LoadNote] VARCHAR(MAX)
		CONSTRAINT [pk_HcProviderId] PRIMARY KEY CLUSTERED 
		(
			[HcProviderId] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END
	
	GO 