/*
DB NAME     : RVRS_ISSUANCE
SCHEMA NAME	: RVRS
VIEW NAME	: VU_DEATH_QC_CAUSE
AUTHOR		: Naba Sarker
CREATED		: Jan   09 2024  
PURPOSE		: Reporting view for death data

----------------------------------------------------------------------------------------------------------------------------------------------
Environment: SQL Server
Here Oracle view converted/transformed into SQL view. ENd of this view the Oracle view has been copied. 
*****************************************************************************************

*/

CREATE view RVRS.VU_DEATH_QC_CAUSE AS

SELECT
    FH_RESPONSIBLE_NAME AS FUNERAL_HOME,
    DEATH_REC_ID,
    SFN_NUM,
    LNAME AS LAST_NAME,
    DOD_4_FD,
    DOD,
    VRV_REC_REPLACE_NBR AS VERSION,
    CAST(CODIA AS NVARCHAR(MAX)) AS CODIA,
    CAST(INTIA AS NVARCHAR(MAX)) AS INTIA,
    CAST(UNITA AS NVARCHAR(MAX)) AS UNITA,
    CAST(CODIB AS NVARCHAR(MAX)) AS CODIB,
    CAST(INTIB AS NVARCHAR(MAX)) AS INTIB,
    CAST(UNITB AS NVARCHAR(MAX)) AS UNITB,
    CAST(CODIC AS NVARCHAR(MAX)) AS CODIC,
    CAST(INTIC AS NVARCHAR(MAX)) AS INTIC,
    CAST(UNITC AS NVARCHAR(MAX)) AS UNITC,
    CAST(CODID AS NVARCHAR(MAX)) AS CODID,
    CAST(INTID AS NVARCHAR(MAX)) AS INTID,
    CAST(UNITD AS NVARCHAR(MAX)) AS UNITD,
    CAST(CONDII AS NVARCHAR(MAX)) AS CONDII,
    OCCUR_REGISTERED_FL,
    FL_VIP_CERTIFIED,
    CERT_CASE_ACCESS
FROM
    RVRS.VIP_VRV_Death_Tbl
WHERE
    DATEDIFF(DAY, VRV_REC_DATE_CREATED, GETDATE()) < 10
    --AND DOD_4_FD IS NOT NULL
   -- AND DOD_4_FD NOT LIKE '%99%'
   -- AND MA_RVRS_SCHEMA.CHECK_DATE(COALESCE(DOD_4_FD, DOD)) = 1
    --AND CONVERT(DATE, DOD_4_FD, 101) BETWEEN DATEADD(DAY, -10, GETDATE()) AND GETDATE()
    AND FL_CURRENT = 1
    AND FL_VOIDED <> 1
    AND FL_ABANDONED <> 'Y';

	/*
	
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" ("FUNERAL_HOME", "DEATH_REC_ID", "SFN_NUM", "LAST_NAME", "DOD_4_FD", "DOD", "VERSION", "CODIA", "INTIA", "UNITA", "CODIB", "INTIB", "UNITB", "CODIC", "INTIC", "UNITC", "CODID", "INTID", "UNITD", "CONDII", "OCCUR_REGISTERED_FL", "FL_VIP_CERTIFIED", "CERT_CASE_ACCESS") AS 
  (
SELECT
FH_RESPONSIBLE_NAME as FUNERAL_HOME,
DEATH_REC_ID,
SFN_NUM, 
LNAME AS LAST_NAME,
DOD_4_FD,
 DOD,
  VRV_REC_REPLACE_NBR as VERSION,
  asciistr(CODIA) as CODIA,
  asciistr(INTIA) as INTIA,
  asciistr(UNITA) as UNITA,
  asciistr(CODIB) as CODIB,
  asciistr(INTIB) as INTIB,
  asciistr(UNITB) as UNITB,
  asciistr(CODIC) as CODIC,
  asciistr(INTIC) as INTIC,
  asciistr(UNITC) as UNITC,
  asciistr(CODID) as CODID,
  asciistr(INTID) as INTID,
  asciistr(UNITD) as UNITD,
  asciistr(CONDII) AS CONDII,
  OCCUR_REGISTERED_FL,
  FL_VIP_CERTIFIED,
  CERT_CASE_ACCESS

from MA_VRVWEB_EVENTS.VRV_DEATH_TBL


WHERE    trunc((sysdate - VRV_REC_DATE_CREATED)) < 10
--DOD_4_FD is not null and DOD_4_FD not like '%99%' and 
-- MA_RVRS_SCHEMA.CHECK_DATE( coalesce( DOD_4_FD,DOD)) = 1
--and to_date( DOD_4_FD,'mm/dd/yyyy') BETWEEN  to_date(sysdate - 10)  and sysdate  
AND  FL_CURRENT=1 and FL_VOIDED <> 1 AND FL_ABANDONED <> 'Y'
);


  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "NSARKER";
  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO PUBLIC;
  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "DSKALTSIS";
  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "MWONG01";
  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "MA_VRWEB_TOOLS";
  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "BWOLDESENBET";
  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "SPAGNANO";
  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "DMATHER";
  GRANT DELETE ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "MA_RVRS_SCHEMA_RW";
  GRANT INSERT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "MA_RVRS_SCHEMA_RW";
  GRANT SELECT ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "MA_RVRS_SCHEMA_RW";
  GRANT UPDATE ON "MA_RVRS_SCHEMA"."VU_DEATH_QC_CAUSE" TO "MA_RVRS_SCHEMA_RW";

  */
